package com.techcell.caixadaloja;

import android.content.Context;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.FirebaseApp;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.SetOptions;
import com.google.firebase.firestore.Source;
import com.google.firebase.firestore.WriteBatch;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

/** Cadastro comercial/estrutural exclusivo do Desenvolvedor. */
public final class TechCellDeveloperCompanyManager {
    private static final String EMPRESAS="techcell_empresas",INDEX="techcell_user_empresas"; private static final long TIMEOUT=25L;
    public static class Dados { public String empresaUuid="",filialUuid="",fantasia="",razao="",cnpj="",telefone="",cidade="",ownerUid="",ownerEmail="",ownerNome="Master"; public TechCellLicenseManager.Licenca licenca=new TechCellLicenseManager.Licenca(); public int caixasEmUso; public boolean emailDefinicaoSenhaEnviado=true; }
    private TechCellDeveloperCompanyManager(){}

    public static Dados ler(Context c,String id)throws Exception{Context app=c.getApplicationContext();TechCellDeveloperAccess.exigir(app);id=req(id,"Empresa inválida.");DocumentReference r=TechCellCloudSync.firestore(app).collection(EMPRESAS).document(id);DocumentSnapshot d=Tasks.await(r.get(Source.SERVER),TIMEOUT,TimeUnit.SECONDS);if(!d.exists())throw new IllegalStateException("Empresa não encontrada.");Dados x=new Dados();x.empresaUuid=id;x.filialUuid=txt(d.get("filial_uuid"));if(x.filialUuid.isEmpty())x.filialUuid=id;x.ownerUid=txt(d.get("owner_uid"));x.ownerEmail=txt(d.get("owner_email"));Object co=d.get("config");if(co instanceof Map){Map<?,?> m=(Map<?,?>)co;x.fantasia=txt(m.get("fantasia"));x.razao=txt(m.get("razao"));x.cnpj=txt(m.get("cnpj"));x.telefone=txt(m.get("telefone"));x.cidade=txt(m.get("cidade"));}if(x.fantasia.isEmpty())x.fantasia=txt(d.get("nome"));if(x.fantasia.isEmpty())x.fantasia=x.ownerEmail.isEmpty()?id:x.ownerEmail;if(!x.ownerUid.isEmpty())try{DocumentSnapshot u=Tasks.await(r.collection("usuarios").document(x.ownerUid).get(Source.SERVER),TIMEOUT,TimeUnit.SECONDS);if(u.exists()){x.ownerNome=txt(u.get("nome"));if(x.ownerNome.isEmpty())x.ownerNome="Master";if(x.ownerEmail.isEmpty())x.ownerEmail=txt(u.get("email"));}}catch(Throwable ignored){}x.licenca=TechCellLicenseManager.lerServidor(app,id);x.caixasEmUso=x.licenca.existe?TechCellLicenseManager.contarSlotsEmUso(app,id):0;return x;}

    public static Dados criar(Context c,String fantasia,String razao,String cnpj,String telefone,String cidade,String masterNome,String masterEmail,String status,String plano,boolean masterAtivo,int caixas)throws Exception{
        Context app=c.getApplicationContext();TechCellDeveloperAccess.exigir(app);String f=req(fantasia,"Informe o nome fantasia da empresa."),mn=req(masterNome,"Informe o nome do Master."),me=email(masterEmail),st=TechCellDeveloper.normalizarStatus(status),pl=TechCellDeveloper.normalizarPlano(plano);caixas=Math.max(0,caixas);FirebaseUser dev=TechCellCloudSync.auth(app).getCurrentUser();if(dev==null)throw new IllegalStateException("Conta Desenvolvedor não conectada.");
        FirebaseApp sec=null;FirebaseAuth au=null;FirebaseUser master=null;DocumentReference er=null;boolean raiz=false,pronto=false;try{
            sec=FirebaseApp.initializeApp(app,TechCellCloudSync.app(app).getOptions(),"TC_NEW_"+UUID.randomUUID());au=FirebaseAuth.getInstance(sec);AuthResult ar=Tasks.await(au.createUserWithEmailAndPassword(me,"Tc!"+UUID.randomUUID().toString().replace("-","")+"9a"),TIMEOUT,TimeUnit.SECONDS);master=ar.getUser();if(master==null)throw new IllegalStateException("Não foi possível criar a conta Master.");String id=UUID.randomUUID().toString(),filial=id;er=TechCellCloudSync.firestore(app).collection(EMPRESAS).document(id);
            // Bootstrap em duas etapas: a regra atual permite criar a raiz quando o owner inicial é o usuário autenticado.
            Map<String,Object> bootstrap=new HashMap<>();bootstrap.put("empresa_uuid",id);bootstrap.put("filial_uuid",filial);bootstrap.put("nome",f);bootstrap.put("owner_uid",dev.getUid());bootstrap.put("owner_email",dev.getEmail()==null?"":dev.getEmail());bootstrap.put("config",cfg(f,razao,cnpj,telefone,cidade));bootstrap.put("bootstrap_developer",true);bootstrap.put("created_by_uid",dev.getUid());bootstrap.put("created_at",FieldValue.serverTimestamp());bootstrap.put("updated_at",FieldValue.serverTimestamp());Tasks.await(er.set(bootstrap),TIMEOUT,TimeUnit.SECONDS);raiz=true;
            WriteBatch b=TechCellCloudSync.firestore(app).batch();Map<String,Object> fim=new HashMap<>();fim.put("owner_uid",master.getUid());fim.put("owner_email",me);fim.put("bootstrap_developer",false);fim.put("updated_at",FieldValue.serverTimestamp());b.set(er,fim,SetOptions.merge());b.set(er.collection("usuarios").document(master.getUid()),masterMap(master.getUid(),id,filial,mn,me));b.set(TechCellCloudSync.firestore(app).collection(INDEX).document(master.getUid()).collection("empresas").document(id),indexMap(master.getUid(),id,filial,mn,me));DocumentReference lr=TechCellLicenseManager.ref(app,id);Map<String,Object> lm=new HashMap<>();lm.put("empresa_uuid",id);lm.put("status",st);lm.put("plano",pl);lm.put("master_ativo",masterAtivo);lm.put("caixas_contratados",caixas);lm.put("gerentes_contratados",0);lm.put("created_by_uid",dev.getUid());lm.put("updated_by_uid",dev.getUid());lm.put("created_at",FieldValue.serverTimestamp());lm.put("updated_at",FieldValue.serverTimestamp());b.set(lr,lm);
            for(int i=1;i<=caixas;i++){DocumentReference sr=lr.collection(TechCellLicenseManager.SLOTS_CAIXA).document(String.format(Locale.ROOT,"C%03d",i));Map<String,Object> sm=new HashMap<>();sm.put("empresa_uuid",id);sm.put("tipo","CAIXA");sm.put("status",TechCellLicenseManager.LIVRE);sm.put("device_uuid","");sm.put("uid","");sm.put("created_at",FieldValue.serverTimestamp());sm.put("updated_at",FieldValue.serverTimestamp());b.set(sr,sm);}b.set(er.collection("auditoria").document(),audit(app,"EMPRESA_CRIADA","EMPRESA",id,f+" • Master: "+me+" • Plano: "+pl+" • Caixas: "+caixas+" • Status: "+st));Tasks.await(b.commit(),TIMEOUT,TimeUnit.SECONDS);pronto=true;
            Dados x=ler(app,id);x.ownerNome=mn;try{Tasks.await(TechCellCloudSync.auth(app).sendPasswordResetEmail(me),TIMEOUT,TimeUnit.SECONDS);x.emailDefinicaoSenhaEnviado=true;}catch(Throwable ignored){x.emailDefinicaoSenhaEnviado=false;}return x;
        }catch(Throwable e){if(!pronto&&raiz&&er!=null)try{Tasks.await(er.delete(),10,TimeUnit.SECONDS);}catch(Throwable ignored){}if(!pronto&&master!=null)try{Tasks.await(master.delete(),10,TimeUnit.SECONDS);}catch(Throwable ignored){}if(e instanceof Exception)throw(Exception)e;throw new IllegalStateException(e);}finally{try{if(au!=null)au.signOut();}catch(Throwable ignored){}try{if(sec!=null)sec.delete();}catch(Throwable ignored){}}
    }

    public static Dados atualizar(Context c,Dados d,String fantasia,String razao,String cnpj,String telefone,String cidade,String status,String plano,boolean masterAtivo,int caixas)throws Exception{Context app=c.getApplicationContext();TechCellDeveloperAccess.exigir(app);if(d==null||d.empresaUuid.isEmpty())throw new IllegalArgumentException("Empresa inválida.");String f=req(fantasia,"Informe o nome fantasia da empresa."),st=TechCellDeveloper.normalizarStatus(status),pl=TechCellDeveloper.normalizarPlano(plano);caixas=Math.max(0,caixas);TechCellDeveloper.Empresa e=new TechCellDeveloper.Empresa();e.empresaUuid=d.empresaUuid;e.filialUuid=d.filialUuid;e.nome=f;e.ownerUid=d.ownerUid;e.ownerEmail=d.ownerEmail;e.licenca=d.licenca;e.caixasEmUso=d.caixasEmUso;TechCellDeveloper.salvarLicenca(app,e,st,pl,masterAtivo,caixas);Map<String,Object> m=new HashMap<>();m.put("nome",f);m.put("config",cfg(f,razao,cnpj,telefone,cidade));m.put("updated_by_uid",devUid(app));m.put("updated_at",FieldValue.serverTimestamp());Tasks.await(TechCellCloudSync.firestore(app).collection(EMPRESAS).document(d.empresaUuid).set(m,SetOptions.merge()),TIMEOUT,TimeUnit.SECONDS);TechCellDeveloperAdmin.registrarAuditoria(app,d.empresaUuid,"EMPRESA_E_LICENCA_EDITADAS","EMPRESA",d.empresaUuid,"Nome: "+f+" • Plano: "+pl+" • Status: "+st+" • Master: "+(masterAtivo?"LIBERADO":"BLOQUEADO")+" • Caixas: "+caixas);return ler(app,d.empresaUuid);}

    public static Dados substituirMaster(Context c,Dados d,String nome,String mail)throws Exception{Context app=c.getApplicationContext();TechCellDeveloperAccess.exigir(app);if(d==null||d.empresaUuid.isEmpty())throw new IllegalArgumentException("Empresa inválida.");nome=req(nome,"Informe o nome do novo Master.");mail=email(mail);if(mail.equalsIgnoreCase(d.ownerEmail))throw new IllegalArgumentException("Informe um e-mail diferente do Master atual.");FirebaseApp sec=null;FirebaseAuth au=null;FirebaseUser novo=null;boolean ok=false;try{sec=FirebaseApp.initializeApp(app,TechCellCloudSync.app(app).getOptions(),"TC_MASTER_"+UUID.randomUUID());au=FirebaseAuth.getInstance(sec);novo=Tasks.await(au.createUserWithEmailAndPassword(mail,"Tc!"+UUID.randomUUID().toString().replace("-","")+"7b"),TIMEOUT,TimeUnit.SECONDS).getUser();if(novo==null)throw new IllegalStateException("Não foi possível criar o novo Master.");DocumentReference er=TechCellCloudSync.firestore(app).collection(EMPRESAS).document(d.empresaUuid);WriteBatch b=TechCellCloudSync.firestore(app).batch();Map<String,Object> em=new HashMap<>();em.put("owner_uid",novo.getUid());em.put("owner_email",mail);em.put("updated_by_uid",devUid(app));em.put("updated_at",FieldValue.serverTimestamp());b.set(er,em,SetOptions.merge());b.set(er.collection("usuarios").document(novo.getUid()),masterMap(novo.getUid(),d.empresaUuid,d.filialUuid,nome,mail));b.set(TechCellCloudSync.firestore(app).collection(INDEX).document(novo.getUid()).collection("empresas").document(d.empresaUuid),indexMap(novo.getUid(),d.empresaUuid,d.filialUuid,nome,mail));if(!d.ownerUid.isEmpty()){b.delete(er.collection("usuarios").document(d.ownerUid));b.delete(TechCellCloudSync.firestore(app).collection(INDEX).document(d.ownerUid).collection("empresas").document(d.empresaUuid));}b.set(er.collection("auditoria").document(),audit(app,"MASTER_SUBSTITUIDO","MASTER",novo.getUid(),"Anterior: "+d.ownerEmail+" • Novo: "+mail));Tasks.await(b.commit(),TIMEOUT,TimeUnit.SECONDS);ok=true;Dados x=ler(app,d.empresaUuid);try{Tasks.await(TechCellCloudSync.auth(app).sendPasswordResetEmail(mail),TIMEOUT,TimeUnit.SECONDS);x.emailDefinicaoSenhaEnviado=true;}catch(Throwable ignored){x.emailDefinicaoSenhaEnviado=false;}return x;}catch(Throwable e){if(!ok&&novo!=null)try{Tasks.await(novo.delete(),10,TimeUnit.SECONDS);}catch(Throwable ignored){}if(e instanceof Exception)throw(Exception)e;throw new IllegalStateException(e);}finally{try{if(au!=null)au.signOut();}catch(Throwable ignored){}try{if(sec!=null)sec.delete();}catch(Throwable ignored){}}}

    public static void reenviarDefinicaoSenha(Context c,String empresa,String mail)throws Exception{Context app=c.getApplicationContext();TechCellDeveloperAccess.exigir(app);mail=email(mail);Tasks.await(TechCellCloudSync.auth(app).sendPasswordResetEmail(mail),TIMEOUT,TimeUnit.SECONDS);TechCellDeveloperAdmin.registrarAuditoria(app,empresa,"DEFINICAO_SENHA_MASTER_REENVIADA","MASTER",mail,"E-mail de definição/redefinição enviado para "+mail);}
    private static Map<String,Object> cfg(String f,String r,String c,String t,String cidade){Map<String,Object> m=new HashMap<>();m.put("fantasia",txt(f));m.put("razao",txt(r));m.put("cnpj",txt(c));m.put("telefone",txt(t));m.put("cidade",txt(cidade));return m;}
    private static Map<String,Object> masterMap(String uid,String empresa,String filial,String nome,String email){Map<String,Object>m=new HashMap<>();m.put("uid",uid);m.put("empresa_uuid",empresa);m.put("filial_uuid",filial==null||filial.isEmpty()?empresa:filial);m.put("nome",nome);m.put("email",email);m.put("perfil","MASTER");m.put("ativo",true);m.put("proprietario",true);m.put("created_at",FieldValue.serverTimestamp());m.put("updated_at",FieldValue.serverTimestamp());return m;}
    private static Map<String,Object> indexMap(String uid,String empresa,String filial,String nome,String email){Map<String,Object>m=new HashMap<>();m.put("uid",uid);m.put("empresa_uuid",empresa);m.put("filial_uuid",filial==null||filial.isEmpty()?empresa:filial);m.put("nome",nome);m.put("email",email);m.put("perfil","MASTER");m.put("proprietario",true);m.put("ativo",true);m.put("updated_at",FieldValue.serverTimestamp());return m;}
    private static Map<String,Object> audit(Context app,String acao,String tipo,String alvo,String desc){FirebaseUser u=TechCellCloudSync.auth(app).getCurrentUser();TechCellDeveloperAccess.Estado d=TechCellDeveloperAccess.local(app);Map<String,Object>m=new HashMap<>();m.put("actor_uid",u==null?"":u.getUid());m.put("actor_email",u==null||u.getEmail()==null?"":u.getEmail());m.put("actor_nome",d.nome==null||d.nome.isEmpty()?"Desenvolvedor":d.nome);m.put("actor_tipo","DEVELOPER");m.put("acao",acao);m.put("alvo_tipo",tipo);m.put("alvo_id",alvo);m.put("descricao",desc);m.put("created_at",FieldValue.serverTimestamp());return m;}
    private static String devUid(Context app){FirebaseUser u=TechCellCloudSync.auth(app).getCurrentUser();if(u==null)throw new IllegalStateException("Conta Desenvolvedor não conectada.");return u.getUid();}
    private static String req(String v,String msg){String s=txt(v);if(s.isEmpty())throw new IllegalArgumentException(msg);return s;} private static String email(String v){String e=txt(v).toLowerCase(Locale.ROOT);if(e.isEmpty()||!e.contains("@")||e.startsWith("@")||e.endsWith("@"))throw new IllegalArgumentException("Informe um e-mail válido para o Master.");return e;} private static String txt(Object v){return v==null?"":String.valueOf(v).trim();}
}
