plugins {
    id 'com.android.application'
}

android {
    namespace 'com.techcell.caixadaloja'
    compileSdk 35

    defaultConfig {
        applicationId 'com.techcell.caixadaloja'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '2.2'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

tasks.named('preBuild').configure {
    doFirst {
        def html = file('src/main/assets/index.html')
        if (html.exists()) {
            def text = html.getText('UTF-8')
            text = text.replace('AIzaSyAcMqWWaeEKfdjIST0NSwkXWWsbSt6iY2k', 'AIzaSyAcMqWWeaEKfdjIST0NSwkXWWsbSt6iY2k')
            html.write(text, 'UTF-8')
        }
    }
}
